version: '2'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
  graphana:
    container_name: graphana
    image: grafana/grafana
    ports:
      - 3000:3000
    links: 
      - prometheus